### ISSUE TITLE
Error when compiling on gearmand version 1.1.19.1

### ISSUE THREAD

**Issue by isayeter** [prometheus/memcached_exporter#165]
Hello,

When I try to compile the project, I'm receiving this error:

My memcached version is : `1.5.22`

![Screenshot 2023-03-22 at 19 09 31](https://user-images.githubusercontent.com/3602109/226967827-cd2ce690-225a-4bfc-b08a-62b441d751a8.jpg)

**Comment by isayeter** [comment]
And when I run `memcached_exporter` after failed make command, it starts, however when I refresh [this template](https://grafana.com/grafana/dashboards/11423-gearman/): I see these errors on console:

```
ts=2023-03-22T17:40:26.912Z caller=exporter.go:1027 level=debug msg="Key not found" key=mem_requested
ts=2023-03-22T17:40:26.912Z caller=exporter.go:1027 level=debug msg="Key not found" key=mem_requested
```

**Comment by matthiasr** [comment]
What does it mean to "compile on gearmand"? Are you using it as a CI system?

I believe you are running into the [acceptance test](https://github.com/prometheus/memcached_exporter/blob/master/cmd/memcached_exporter/main_test.go). It expects an empty memcached, and I think because gearman also uses memcached, it is actually testing against gearman's memcached.

You can provide a dedicated (ephemeral) memcached for the tests
and set `MEMCACHED_PORT` (I believe the name is misleading, set it to `host:port` e.g. `localhost:11234`). Or if this is not an option, and you don't care about this acceptance test, use `make build`.

The log line you posted is at debug level, I don't think you need to worry about it too much. I haven't tracked this down in detail but I suspect it's due to differences between memcached versions.

**Comment by isayeter** [comment]
So sorry, for the wrong name :) I was dealing with gearmand, my brain confused :) 

My memcached version is : `1.5.22`

**Comment by isayeter** [comment]
It works now, thank you so much.
